# Generated by Django 5.2.8 on 2026-05-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_measurement_project_device_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'name')},
        ),
    ]
