# Generated by Django 5.2.8 on 2026-05-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_measurement_project_device_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do Dispositivo'),
        ),
    ]
