# Generated by Django 5.2.8 on 2026-06-09 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Convidado')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('declined', 'Recusado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
            ],
            options={
                'verbose_name': 'Convite de Projeto',
                'verbose_name_plural': 'Convites de Projeto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visto por último'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['device', '-timestamp'], name='measurement_device_ts_idx'),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_project_invites', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por'),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.project', verbose_name='Projeto'),
        ),
        migrations.AddConstraint(
            model_name='projectinvite',
            constraint=models.UniqueConstraint(fields=('project', 'email', 'status'), name='unique_project_invite_by_status'),
        ),
    ]
