# Generated by Django 5.2.8 on 2026-06-14 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_device_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coordenador', 'Coordenador'), ('Pesquisador', 'Pesquisador')], default='Pesquisador', max_length=20, verbose_name='Papel')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Convidado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project', verbose_name='Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro do Projeto',
                'verbose_name_plural': 'Membros do Projeto',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
